//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.3.1-b171012.0423 
//         See <a href="https://javaee.github.io/jaxb-v2/">https://javaee.github.io/jaxb-v2/</a> 
//         Any modifications to this file will be lost upon recompilation of the source schema. 
//         Generated on: 2022.02.05 at 04:56:45 PM CET 
//


package entity;

import jakarta.xml.bind.annotation.XmlRegistry;


/**
 * This object contains factory methods for each 
 * Java content interface and Java element interface 
 * generated in the d package. 
 * <p>An ObjectFactory allows you to programatically 
 * construct new instances of the Java representation 
 * for XML content. The Java representation of XML 
 * content can consist of schema derived interfaces 
 * and classes representing the binding of schema 
 * type definitions, element declarations and model 
 * groups.  Factory methods for each of these are 
 * provided in this class.
 * 
 */
@XmlRegistry
public class ObjectFactory {


    /**
     * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package: d
     * 
     */
    public ObjectFactory() {
    }

    /**
     * Create an instance of {@link Profile }
     * 
     */
    public Profile createProfile() {
        return new Profile();
    }

    /**
     * Create an instance of {@link PermissionSet }
     * 
     */
    public PermissionSet createPermissionSet() {
        return new PermissionSet();
    }

    /**
     * Create an instance of {@link ApplicationVisibilities }
     * 
     */
    public ApplicationVisibilities createProfileApplicationVisibilities() {
        return new ApplicationVisibilities();
    }

    /**
     * Create an instance of {@link CategoryGroupVisibilities }
     * 
     */
    public CategoryGroupVisibilities createProfileCategoryGroupVisibilities() {
        return new CategoryGroupVisibilities();
    }

    /**
     * Create an instance of {@link ClassAccesses }
     * 
     */
    public ClassAccesses createProfileClassAccesses() {
        return new ClassAccesses();
    }

    /**
     * Create an instance of {@link CustomMetadataTypeAccesses }
     * 
     */
    public CustomMetadataTypeAccesses createProfileCustomMetadataTypeAccesses() {
        return new CustomMetadataTypeAccesses();
    }

    /**
     * Create an instance of {@link CustomPermissions }
     * 
     */
    public CustomPermissions createProfileCustomPermissions() {
        return new CustomPermissions();
    }

    /**
     * Create an instance of {@link FieldPermissions }
     * 
     */
    public FieldPermissions createProfileFieldPermissions() {
        return new FieldPermissions();
    }

    /**
     * Create an instance of {@link LayoutAssignments }
     * 
     */
    public LayoutAssignments createProfileLayoutAssignments() {
        return new LayoutAssignments();
    }

    /**
     * Create an instance of {@link LoginIpRanges }
     * 
     */
    public LoginIpRanges createProfileLoginIpRanges() {
        return new LoginIpRanges();
    }

    /**
     * Create an instance of {@link ObjectPermissions }
     * 
     */
    public ObjectPermissions createProfileObjectPermissions() {
        return new ObjectPermissions();
    }

    /**
     * Create an instance of {@link PageAccesses }
     * 
     */
    public PageAccesses createProfilePageAccesses() {
        return new PageAccesses();
    }

    /**
     * Create an instance of {@link RecordTypeVisibilities }
     * 
     */
    public RecordTypeVisibilities createProfileRecordTypeVisibilities() {
        return new RecordTypeVisibilities();
    }

    /**
     * Create an instance of {@link TabVisibilities }
     * 
     */
    public TabVisibilities createProfileTabVisibilities() {
        return new TabVisibilities();
    }

    /**
     * Create an instance of {@link UserPermissions }
     * 
     */
    public UserPermissions createProfileUserPermissions() {
        return new UserPermissions();
    }

    /**
     * Create an instance of {@link ApplicationVisibilities }
     * 
     */
    public ApplicationVisibilities createPermissionSetApplicationVisibilities() {
        return new ApplicationVisibilities();
    }

    /**
     * Create an instance of {@link CategoryGroupVisibilities }
     * 
     */
    public CategoryGroupVisibilities createPermissionSetCategoryGroupVisibilities() {
        return new CategoryGroupVisibilities();
    }

    /**
     * Create an instance of {@link ClassAccesses }
     * 
     */
    public ClassAccesses createPermissionSetClassAccesses() {
        return new ClassAccesses();
    }

    /**
     * Create an instance of {@link CustomMetadataTypeAccesses }
     * 
     */
    public CustomMetadataTypeAccesses createPermissionSetCustomMetadataTypeAccesses() {
        return new CustomMetadataTypeAccesses();
    }

    /**
     * Create an instance of {@link CustomPermissions }
     * 
     */
    public CustomPermissions createPermissionSetCustomPermissions() {
        return new CustomPermissions();
    }

    /**
     * Create an instance of {@link FieldPermissions }
     * 
     */
    public FieldPermissions createPermissionSetFieldPermissions() {
        return new FieldPermissions();
    }

    /**
     * Create an instance of {@link LayoutAssignments }
     * 
     */
    public LayoutAssignments createPermissionSetLayoutAssignments() {
        return new LayoutAssignments();
    }

    /**
     * Create an instance of {@link LoginIpRanges }
     * 
     */
    public LoginIpRanges createPermissionSetLoginIpRanges() {
        return new LoginIpRanges();
    }

    /**
     * Create an instance of {@link ObjectPermissions }
     * 
     */
    public ObjectPermissions createPermissionSetObjectPermissions() {
        return new ObjectPermissions();
    }

    /**
     * Create an instance of {@link PageAccesses }
     * 
     */
    public PageAccesses createPermissionSetPageAccesses() {
        return new PageAccesses();
    }

    /**
     * Create an instance of {@link RecordTypeVisibilities }
     * 
     */
    public RecordTypeVisibilities createPermissionSetRecordTypeVisibilities() {
        return new RecordTypeVisibilities();
    }

    /**
     * Create an instance of {@link TabVisibilities }
     * 
     */
    public TabVisibilities createPermissionSetTabVisibilities() {
        return new TabVisibilities();
    }

    /**
     * Create an instance of {@link UserPermissions }
     * 
     */
    public UserPermissions createPermissionSetUserPermissions() {
        return new UserPermissions();
    }

}
