//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.3.1-b171012.0423 
//         See <a href="https://javaee.github.io/jaxb-v2/">https://javaee.github.io/jaxb-v2/</a> 
//         Any modifications to this file will be lost upon recompilation of the source schema. 
//         Generated on: 2022.01.30 at 01:02:57 AM CET 
//

@jakarta.xml.bind.annotation.XmlSchema(namespace = "http://soap.sforce.com/2006/04/metadata",
        elementFormDefault = jakarta.xml.bind.annotation.XmlNsForm.QUALIFIED)
package entity;