package entity;//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.3.1-b171012.0423 
//         See <a href="https://javaee.github.io/jaxb-v2/">https://javaee.github.io/jaxb-v2/</a> 
//         Any modifications to this file will be lost upon recompilation of the source schema. 
//         Generated on: 2022.01.30 at 01:02:57 AM CET 
//


import java.util.ArrayList;
import java.util.List;

import jakarta.xml.bind.annotation.*;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected         content contained within this class.
 * 
 * <pre>
 * &lt;complexType&gt;
 *   &lt;complexContent&gt;
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *       &lt;sequence&gt;
 *         &lt;element name="applicationVisibilities" maxOccurs="unbounded"&gt;
 *           &lt;complexType&gt;
 *             &lt;complexContent&gt;
 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *                 &lt;sequence&gt;
 *                   &lt;element name="application" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
 *                   &lt;element name="default" type="{http://www.w3.org/2001/XMLSchema}boolean"/&gt;
 *                   &lt;element name="visible" type="{http://www.w3.org/2001/XMLSchema}boolean"/&gt;
 *                 &lt;/sequence&gt;
 *               &lt;/restriction&gt;
 *             &lt;/complexContent&gt;
 *           &lt;/complexType&gt;
 *         &lt;/element&gt;
 *         &lt;element name="categoryGroupVisibilities" maxOccurs="unbounded"&gt;
 *           &lt;complexType&gt;
 *             &lt;complexContent&gt;
 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *                 &lt;sequence&gt;
 *                   &lt;element name="dataCategories" type="{http://www.w3.org/2001/XMLSchema}string" maxOccurs="unbounded" minOccurs="0"/&gt;
 *                   &lt;element name="dataCategoryGroup" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
 *                   &lt;element name="visibility" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
 *                 &lt;/sequence&gt;
 *               &lt;/restriction&gt;
 *             &lt;/complexContent&gt;
 *           &lt;/complexType&gt;
 *         &lt;/element&gt;
 *         &lt;element name="classAccesses" maxOccurs="unbounded"&gt;
 *           &lt;complexType&gt;
 *             &lt;complexContent&gt;
 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *                 &lt;sequence&gt;
 *                   &lt;element name="apexClass" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
 *                   &lt;element name="enabled" type="{http://www.w3.org/2001/XMLSchema}boolean"/&gt;
 *                 &lt;/sequence&gt;
 *               &lt;/restriction&gt;
 *             &lt;/complexContent&gt;
 *           &lt;/complexType&gt;
 *         &lt;/element&gt;
 *         &lt;element name="custom" type="{http://www.w3.org/2001/XMLSchema}boolean"/&gt;
 *         &lt;element name="customMetadataTypeAccesses" maxOccurs="unbounded"&gt;
 *           &lt;complexType&gt;
 *             &lt;complexContent&gt;
 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *                 &lt;sequence&gt;
 *                   &lt;element name="enabled" type="{http://www.w3.org/2001/XMLSchema}boolean"/&gt;
 *                   &lt;element name="name" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
 *                 &lt;/sequence&gt;
 *               &lt;/restriction&gt;
 *             &lt;/complexContent&gt;
 *           &lt;/complexType&gt;
 *         &lt;/element&gt;
 *         &lt;element name="customPermissions" maxOccurs="unbounded"&gt;
 *           &lt;complexType&gt;
 *             &lt;complexContent&gt;
 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *                 &lt;sequence&gt;
 *                   &lt;element name="enabled" type="{http://www.w3.org/2001/XMLSchema}boolean"/&gt;
 *                   &lt;element name="name" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
 *                 &lt;/sequence&gt;
 *               &lt;/restriction&gt;
 *             &lt;/complexContent&gt;
 *           &lt;/complexType&gt;
 *         &lt;/element&gt;
 *         &lt;element name="fieldPermissions" maxOccurs="unbounded"&gt;
 *           &lt;complexType&gt;
 *             &lt;complexContent&gt;
 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *                 &lt;sequence&gt;
 *                   &lt;element name="editable" type="{http://www.w3.org/2001/XMLSchema}boolean"/&gt;
 *                   &lt;element name="field" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
 *                   &lt;element name="readable" type="{http://www.w3.org/2001/XMLSchema}boolean"/&gt;
 *                 &lt;/sequence&gt;
 *               &lt;/restriction&gt;
 *             &lt;/complexContent&gt;
 *           &lt;/complexType&gt;
 *         &lt;/element&gt;
 *         &lt;element name="layoutAssignments" maxOccurs="unbounded"&gt;
 *           &lt;complexType&gt;
 *             &lt;complexContent&gt;
 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *                 &lt;sequence&gt;
 *                   &lt;element name="layout" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
 *                   &lt;element name="recordType" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/&gt;
 *                 &lt;/sequence&gt;
 *               &lt;/restriction&gt;
 *             &lt;/complexContent&gt;
 *           &lt;/complexType&gt;
 *         &lt;/element&gt;
 *         &lt;element name="loginIpRanges" maxOccurs="unbounded"&gt;
 *           &lt;complexType&gt;
 *             &lt;complexContent&gt;
 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *                 &lt;sequence&gt;
 *                   &lt;element name="endAddress" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
 *                   &lt;element name="startAddress" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
 *                 &lt;/sequence&gt;
 *               &lt;/restriction&gt;
 *             &lt;/complexContent&gt;
 *           &lt;/complexType&gt;
 *         &lt;/element&gt;
 *         &lt;element name="objectPermissions" maxOccurs="unbounded"&gt;
 *           &lt;complexType&gt;
 *             &lt;complexContent&gt;
 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *                 &lt;sequence&gt;
 *                   &lt;element name="allowCreate" type="{http://www.w3.org/2001/XMLSchema}boolean"/&gt;
 *                   &lt;element name="allowDelete" type="{http://www.w3.org/2001/XMLSchema}boolean"/&gt;
 *                   &lt;element name="allowEdit" type="{http://www.w3.org/2001/XMLSchema}boolean"/&gt;
 *                   &lt;element name="allowRead" type="{http://www.w3.org/2001/XMLSchema}boolean"/&gt;
 *                   &lt;element name="modifyAllRecords" type="{http://www.w3.org/2001/XMLSchema}boolean"/&gt;
 *                   &lt;element name="object" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
 *                   &lt;element name="viewAllRecords" type="{http://www.w3.org/2001/XMLSchema}boolean"/&gt;
 *                 &lt;/sequence&gt;
 *               &lt;/restriction&gt;
 *             &lt;/complexContent&gt;
 *           &lt;/complexType&gt;
 *         &lt;/element&gt;
 *         &lt;element name="pageAccesses" maxOccurs="unbounded"&gt;
 *           &lt;complexType&gt;
 *             &lt;complexContent&gt;
 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *                 &lt;sequence&gt;
 *                   &lt;element name="apexPage" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
 *                   &lt;element name="enabled" type="{http://www.w3.org/2001/XMLSchema}boolean"/&gt;
 *                 &lt;/sequence&gt;
 *               &lt;/restriction&gt;
 *             &lt;/complexContent&gt;
 *           &lt;/complexType&gt;
 *         &lt;/element&gt;
 *         &lt;element name="recordTypeVisibilities" maxOccurs="unbounded"&gt;
 *           &lt;complexType&gt;
 *             &lt;complexContent&gt;
 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *                 &lt;sequence&gt;
 *                   &lt;element name="default" type="{http://www.w3.org/2001/XMLSchema}boolean"/&gt;
 *                   &lt;element name="personAccountDefault" type="{http://www.w3.org/2001/XMLSchema}boolean" minOccurs="0"/&gt;
 *                   &lt;element name="recordType" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
 *                   &lt;element name="visible" type="{http://www.w3.org/2001/XMLSchema}boolean"/&gt;
 *                 &lt;/sequence&gt;
 *               &lt;/restriction&gt;
 *             &lt;/complexContent&gt;
 *           &lt;/complexType&gt;
 *         &lt;/element&gt;
 *         &lt;element name="tabVisibilities" maxOccurs="unbounded"&gt;
 *           &lt;complexType&gt;
 *             &lt;complexContent&gt;
 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *                 &lt;sequence&gt;
 *                   &lt;element name="tab" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
 *                   &lt;element name="visibility" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
 *                 &lt;/sequence&gt;
 *               &lt;/restriction&gt;
 *             &lt;/complexContent&gt;
 *           &lt;/complexType&gt;
 *         &lt;/element&gt;
 *         &lt;element name="userLicense" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
 *         &lt;element name="userPermissions" maxOccurs="unbounded"&gt;
 *           &lt;complexType&gt;
 *             &lt;complexContent&gt;
 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *                 &lt;sequence&gt;
 *                   &lt;element name="enabled" type="{http://www.w3.org/2001/XMLSchema}boolean"/&gt;
 *                   &lt;element name="name" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
 *                 &lt;/sequence&gt;
 *               &lt;/restriction&gt;
 *             &lt;/complexContent&gt;
 *           &lt;/complexType&gt;
 *         &lt;/element&gt;
 *       &lt;/sequence&gt;
 *     &lt;/restriction&gt;
 *   &lt;/complexContent&gt;
 * &lt;/complexType&gt;
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "applicationVisibilities",
    "categoryGroupVisibilities",
    "classAccesses",
    "custom",
    "customMetadataTypeAccesses",
    "customPermissions",
    "fieldPermissions",
    "layoutAssignments",
    "loginIpRanges",
    "objectPermissions",
    "pageAccesses",
    "recordTypeVisibilities",
    "tabVisibilities",
    "userLicense",
    "userPermissions"
})
@XmlRootElement(name = "Profile")
public class Profile {

    protected List<ApplicationVisibilities> applicationVisibilities;
    @XmlElement(required = true)
    protected List<CategoryGroupVisibilities> categoryGroupVisibilities;
    @XmlElement(required = true)
    protected List<ClassAccesses> classAccesses;
    protected boolean custom;
    @XmlElement(required = true)
    protected List<CustomMetadataTypeAccesses> customMetadataTypeAccesses;
    @XmlElement(required = true)
    protected List<CustomPermissions> customPermissions;
    @XmlElement(required = true)
    protected List<FieldPermissions> fieldPermissions;
    @XmlElement(required = true)
    protected List<LayoutAssignments> layoutAssignments;
    @XmlElement(required = true)
    protected List<LoginIpRanges> loginIpRanges;
    @XmlElement(required = true)
    protected List<ObjectPermissions> objectPermissions;
    @XmlElement(required = true)
    protected List<PageAccesses> pageAccesses;
    @XmlElement(required = true)
    protected List<RecordTypeVisibilities> recordTypeVisibilities;
    @XmlElement(required = true)
    protected List<TabVisibilities> tabVisibilities;
    @XmlElement(required = true)
    protected String userLicense;
    @XmlElement(required = true)
    protected List<UserPermissions> userPermissions;

    /**
     * Gets the value of the applicationVisibilities property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the applicationVisibilities property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getApplicationVisibilities().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link ApplicationVisibilities }
     * 
     * 
     */
    public List<ApplicationVisibilities> getApplicationVisibilities() {
        if (applicationVisibilities == null) {
            applicationVisibilities = new ArrayList<ApplicationVisibilities>();
        }
        return this.applicationVisibilities;
    }

    /**
     * Gets the value of the categoryGroupVisibilities property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the categoryGroupVisibilities property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getCategoryGroupVisibilities().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link CategoryGroupVisibilities }
     * 
     * 
     */
    public List<CategoryGroupVisibilities> getCategoryGroupVisibilities() {
        if (categoryGroupVisibilities == null) {
            categoryGroupVisibilities = new ArrayList<CategoryGroupVisibilities>();
        }
        return this.categoryGroupVisibilities;
    }

    /**
     * Gets the value of the classAccesses property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the classAccesses property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getClassAccesses().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link ClassAccesses }
     * 
     * 
     */
    public List<ClassAccesses> getClassAccesses() {
        if (classAccesses == null) {
            classAccesses = new ArrayList<ClassAccesses>();
        }
        return this.classAccesses;
    }

    /**
     * Gets the value of the custom property.
     * 
     */
    public boolean isCustom() {
        return custom;
    }

    /**
     * Sets the value of the custom property.
     * 
     */
    public void setCustom(boolean value) {
        this.custom = value;
    }

    /**
     * Gets the value of the customMetadataTypeAccesses property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the customMetadataTypeAccesses property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getCustomMetadataTypeAccesses().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link CustomMetadataTypeAccesses }
     * 
     * 
     */
    public List<CustomMetadataTypeAccesses> getCustomMetadataTypeAccesses() {
        if (customMetadataTypeAccesses == null) {
            customMetadataTypeAccesses = new ArrayList<CustomMetadataTypeAccesses>();
        }
        return this.customMetadataTypeAccesses;
    }

    /**
     * Gets the value of the customPermissions property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the customPermissions property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getCustomPermissions().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link CustomPermissions }
     * 
     * 
     */
    public List<CustomPermissions> getCustomPermissions() {
        if (customPermissions == null) {
            customPermissions = new ArrayList<CustomPermissions>();
        }
        return this.customPermissions;
    }

    /**
     * Gets the value of the fieldPermissions property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the fieldPermissions property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getFieldPermissions().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link FieldPermissions }
     * 
     * 
     */
    public List<FieldPermissions> getFieldPermissions() {
        if (fieldPermissions == null) {
            fieldPermissions = new ArrayList<FieldPermissions>();
        }
        return this.fieldPermissions;
    }

    /**
     * Gets the value of the layoutAssignments property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the layoutAssignments property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getLayoutAssignments().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link LayoutAssignments }
     * 
     * 
     */
    public List<LayoutAssignments> getLayoutAssignments() {
        if (layoutAssignments == null) {
            layoutAssignments = new ArrayList<LayoutAssignments>();
        }
        return this.layoutAssignments;
    }

    /**
     * Gets the value of the loginIpRanges property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the loginIpRanges property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getLoginIpRanges().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link LoginIpRanges }
     * 
     * 
     */
    public List<LoginIpRanges> getLoginIpRanges() {
        if (loginIpRanges == null) {
            loginIpRanges = new ArrayList<LoginIpRanges>();
        }
        return this.loginIpRanges;
    }

    /**
     * Gets the value of the objectPermissions property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the objectPermissions property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getObjectPermissions().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link ObjectPermissions }
     * 
     * 
     */
    public List<ObjectPermissions> getObjectPermissions() {
        if (objectPermissions == null) {
            objectPermissions = new ArrayList<ObjectPermissions>();
        }
        return this.objectPermissions;
    }

    /**
     * Gets the value of the pageAccesses property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the pageAccesses property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getPageAccesses().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link PageAccesses }
     * 
     * 
     */
    public List<PageAccesses> getPageAccesses() {
        if (pageAccesses == null) {
            pageAccesses = new ArrayList<PageAccesses>();
        }
        return this.pageAccesses;
    }

    /**
     * Gets the value of the recordTypeVisibilities property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the recordTypeVisibilities property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getRecordTypeVisibilities().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link RecordTypeVisibilities }
     * 
     * 
     */
    public List<RecordTypeVisibilities> getRecordTypeVisibilities() {
        if (recordTypeVisibilities == null) {
            recordTypeVisibilities = new ArrayList<RecordTypeVisibilities>();
        }
        return this.recordTypeVisibilities;
    }

    /**
     * Gets the value of the tabVisibilities property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the tabVisibilities property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getTabVisibilities().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link TabVisibilities }
     * 
     * 
     */
    public List<TabVisibilities> getTabVisibilities() {
        if (tabVisibilities == null) {
            tabVisibilities = new ArrayList<TabVisibilities>();
        }
        return this.tabVisibilities;
    }

    /**
     * Gets the value of the userLicense property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getUserLicense() {
        return userLicense;
    }

    /**
     * Sets the value of the userLicense property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setUserLicense(String value) {
        this.userLicense = value;
    }

    /**
     * Gets the value of the userPermissions property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the userPermissions property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getUserPermissions().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link UserPermissions }
     * 
     * 
     */
    public List<UserPermissions> getUserPermissions() {
        if (userPermissions == null) {
            userPermissions = new ArrayList<UserPermissions>();
        }
        return this.userPermissions;
    }


    /**
     * <p>Java class for anonymous complex type.
     * 
     * <p>The following schema fragment specifies the expected         content contained within this class.
     * 
     * <pre>
     * &lt;complexType&gt;
     *   &lt;complexContent&gt;
     *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
     *       &lt;sequence&gt;
     *         &lt;element name="application" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
     *         &lt;element name="default" type="{http://www.w3.org/2001/XMLSchema}boolean"/&gt;
     *         &lt;element name="visible" type="{http://www.w3.org/2001/XMLSchema}boolean"/&gt;
     *       &lt;/sequence&gt;
     *     &lt;/restriction&gt;
     *   &lt;/complexContent&gt;
     * &lt;/complexType&gt;
     * </pre>
     * 
     * 
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = {
        "application",
        "_default",
        "visible"
    })
    public static class ApplicationVisibilities {

        @XmlElement(required = true)
        protected String application;
        @XmlElement(name = "default")
        protected boolean _default;
        protected boolean visible;

        /**
         * Gets the value of the application property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getApplication() {
            return application;
        }

        /**
         * Sets the value of the application property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setApplication(String value) {
            this.application = value;
        }

        /**
         * Gets the value of the default property.
         * 
         */
        public boolean isDefault() {
            return _default;
        }

        /**
         * Sets the value of the default property.
         * 
         */
        public void setDefault(boolean value) {
            this._default = value;
        }

        /**
         * Gets the value of the visible property.
         * 
         */
        public boolean isVisible() {
            return visible;
        }

        /**
         * Sets the value of the visible property.
         * 
         */
        public void setVisible(boolean value) {
            this.visible = value;
        }

    }


    /**
     * <p>Java class for anonymous complex type.
     * 
     * <p>The following schema fragment specifies the expected         content contained within this class.
     * 
     * <pre>
     * &lt;complexType&gt;
     *   &lt;complexContent&gt;
     *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
     *       &lt;sequence&gt;
     *         &lt;element name="dataCategories" type="{http://www.w3.org/2001/XMLSchema}string" maxOccurs="unbounded" minOccurs="0"/&gt;
     *         &lt;element name="dataCategoryGroup" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
     *         &lt;element name="visibility" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
     *       &lt;/sequence&gt;
     *     &lt;/restriction&gt;
     *   &lt;/complexContent&gt;
     * &lt;/complexType&gt;
     * </pre>
     * 
     * 
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = {
        "dataCategories",
        "dataCategoryGroup",
        "visibility"
    })
    public static class CategoryGroupVisibilities {

        protected List<String> dataCategories;
        @XmlElement(required = true)
        protected String dataCategoryGroup;
        @XmlElement(required = true)
        protected String visibility;

        /**
         * Gets the value of the dataCategories property.
         * 
         * <p>
         * This accessor method returns a reference to the live list,
         * not a snapshot. Therefore any modification you make to the
         * returned list will be present inside the JAXB object.
         * This is why there is not a <CODE>set</CODE> method for the dataCategories property.
         * 
         * <p>
         * For example, to add a new item, do as follows:
         * <pre>
         *    getDataCategories().add(newItem);
         * </pre>
         * 
         * 
         * <p>
         * Objects of the following type(s) are allowed in the list
         * {@link String }
         * 
         * 
         */
        public List<String> getDataCategories() {
            if (dataCategories == null) {
                dataCategories = new ArrayList<String>();
            }
            return this.dataCategories;
        }

        /**
         * Gets the value of the dataCategoryGroup property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getDataCategoryGroup() {
            return dataCategoryGroup;
        }

        /**
         * Sets the value of the dataCategoryGroup property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setDataCategoryGroup(String value) {
            this.dataCategoryGroup = value;
        }

        /**
         * Gets the value of the visibility property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getVisibility() {
            return visibility;
        }

        /**
         * Sets the value of the visibility property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setVisibility(String value) {
            this.visibility = value;
        }

    }


    /**
     * <p>Java class for anonymous complex type.
     * 
     * <p>The following schema fragment specifies the expected         content contained within this class.
     * 
     * <pre>
     * &lt;complexType&gt;
     *   &lt;complexContent&gt;
     *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
     *       &lt;sequence&gt;
     *         &lt;element name="apexClass" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
     *         &lt;element name="enabled" type="{http://www.w3.org/2001/XMLSchema}boolean"/&gt;
     *       &lt;/sequence&gt;
     *     &lt;/restriction&gt;
     *   &lt;/complexContent&gt;
     * &lt;/complexType&gt;
     * </pre>
     * 
     * 
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = {
        "apexClass",
        "enabled"
    })
    public static class ClassAccesses {

        @XmlElement(required = true)
        protected String apexClass;
        protected boolean enabled;

        /**
         * Gets the value of the apexClass property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getApexClass() {
            return apexClass;
        }

        /**
         * Sets the value of the apexClass property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setApexClass(String value) {
            this.apexClass = value;
        }

        /**
         * Gets the value of the enabled property.
         * 
         */
        public boolean isEnabled() {
            return enabled;
        }

        /**
         * Sets the value of the enabled property.
         * 
         */
        public void setEnabled(boolean value) {
            this.enabled = value;
        }

    }


    /**
     * <p>Java class for anonymous complex type.
     * 
     * <p>The following schema fragment specifies the expected         content contained within this class.
     * 
     * <pre>
     * &lt;complexType&gt;
     *   &lt;complexContent&gt;
     *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
     *       &lt;sequence&gt;
     *         &lt;element name="enabled" type="{http://www.w3.org/2001/XMLSchema}boolean"/&gt;
     *         &lt;element name="name" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
     *       &lt;/sequence&gt;
     *     &lt;/restriction&gt;
     *   &lt;/complexContent&gt;
     * &lt;/complexType&gt;
     * </pre>
     * 
     * 
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = {
        "enabled",
        "name"
    })
    public static class CustomMetadataTypeAccesses {

        protected boolean enabled;
        @XmlElement(required = true)
        protected String name;

        /**
         * Gets the value of the enabled property.
         * 
         */
        public boolean isEnabled() {
            return enabled;
        }

        /**
         * Sets the value of the enabled property.
         * 
         */
        public void setEnabled(boolean value) {
            this.enabled = value;
        }

        /**
         * Gets the value of the name property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getName() {
            return name;
        }

        /**
         * Sets the value of the name property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setName(String value) {
            this.name = value;
        }

    }


    /**
     * <p>Java class for anonymous complex type.
     * 
     * <p>The following schema fragment specifies the expected         content contained within this class.
     * 
     * <pre>
     * &lt;complexType&gt;
     *   &lt;complexContent&gt;
     *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
     *       &lt;sequence&gt;
     *         &lt;element name="enabled" type="{http://www.w3.org/2001/XMLSchema}boolean"/&gt;
     *         &lt;element name="name" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
     *       &lt;/sequence&gt;
     *     &lt;/restriction&gt;
     *   &lt;/complexContent&gt;
     * &lt;/complexType&gt;
     * </pre>
     * 
     * 
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = {
        "enabled",
        "name"
    })
    public static class CustomPermissions {

        protected boolean enabled;
        @XmlElement(required = true)
        protected String name;

        /**
         * Gets the value of the enabled property.
         * 
         */
        public boolean isEnabled() {
            return enabled;
        }

        /**
         * Sets the value of the enabled property.
         * 
         */
        public void setEnabled(boolean value) {
            this.enabled = value;
        }

        /**
         * Gets the value of the name property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getName() {
            return name;
        }

        /**
         * Sets the value of the name property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setName(String value) {
            this.name = value;
        }

    }


    /**
     * <p>Java class for anonymous complex type.
     * 
     * <p>The following schema fragment specifies the expected         content contained within this class.
     * 
     * <pre>
     * &lt;complexType&gt;
     *   &lt;complexContent&gt;
     *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
     *       &lt;sequence&gt;
     *         &lt;element name="editable" type="{http://www.w3.org/2001/XMLSchema}boolean"/&gt;
     *         &lt;element name="field" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
     *         &lt;element name="readable" type="{http://www.w3.org/2001/XMLSchema}boolean"/&gt;
     *       &lt;/sequence&gt;
     *     &lt;/restriction&gt;
     *   &lt;/complexContent&gt;
     * &lt;/complexType&gt;
     * </pre>
     * 
     * 
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = {
        "editable",
        "field",
        "readable"
    })
    public static class FieldPermissions {

        protected boolean editable;
        @XmlElement(required = true)
        protected String field;
        protected boolean readable;

        /**
         * Gets the value of the editable property.
         * 
         */
        public boolean isEditable() {
            return editable;
        }

        /**
         * Sets the value of the editable property.
         * 
         */
        public void setEditable(boolean value) {
            this.editable = value;
        }

        /**
         * Gets the value of the field property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getField() {
            return field;
        }

        /**
         * Sets the value of the field property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setField(String value) {
            this.field = value;
        }

        /**
         * Gets the value of the readable property.
         * 
         */
        public boolean isReadable() {
            return readable;
        }

        /**
         * Sets the value of the readable property.
         * 
         */
        public void setReadable(boolean value) {
            this.readable = value;
        }

    }


    /**
     * <p>Java class for anonymous complex type.
     * 
     * <p>The following schema fragment specifies the expected         content contained within this class.
     * 
     * <pre>
     * &lt;complexType&gt;
     *   &lt;complexContent&gt;
     *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
     *       &lt;sequence&gt;
     *         &lt;element name="layout" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
     *         &lt;element name="recordType" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/&gt;
     *       &lt;/sequence&gt;
     *     &lt;/restriction&gt;
     *   &lt;/complexContent&gt;
     * &lt;/complexType&gt;
     * </pre>
     * 
     * 
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = {
        "layout",
        "recordType"
    })
    public static class LayoutAssignments {

        @XmlElement(required = true)
        protected String layout;
        protected String recordType;

        /**
         * Gets the value of the layout property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getLayout() {
            return layout;
        }

        /**
         * Sets the value of the layout property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setLayout(String value) {
            this.layout = value;
        }

        /**
         * Gets the value of the recordType property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getRecordType() {
            return recordType;
        }

        /**
         * Sets the value of the recordType property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setRecordType(String value) {
            this.recordType = value;
        }

    }


    /**
     * <p>Java class for anonymous complex type.
     * 
     * <p>The following schema fragment specifies the expected         content contained within this class.
     * 
     * <pre>
     * &lt;complexType&gt;
     *   &lt;complexContent&gt;
     *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
     *       &lt;sequence&gt;
     *         &lt;element name="endAddress" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
     *         &lt;element name="startAddress" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
     *       &lt;/sequence&gt;
     *     &lt;/restriction&gt;
     *   &lt;/complexContent&gt;
     * &lt;/complexType&gt;
     * </pre>
     * 
     * 
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = {
        "endAddress",
        "startAddress"
    })
    public static class LoginIpRanges {

        @XmlElement(required = true)
        protected String endAddress;
        @XmlElement(required = true)
        protected String startAddress;

        /**
         * Gets the value of the endAddress property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getEndAddress() {
            return endAddress;
        }

        /**
         * Sets the value of the endAddress property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setEndAddress(String value) {
            this.endAddress = value;
        }

        /**
         * Gets the value of the startAddress property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getStartAddress() {
            return startAddress;
        }

        /**
         * Sets the value of the startAddress property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setStartAddress(String value) {
            this.startAddress = value;
        }

    }


    /**
     * <p>Java class for anonymous complex type.
     * 
     * <p>The following schema fragment specifies the expected         content contained within this class.
     * 
     * <pre>
     * &lt;complexType&gt;
     *   &lt;complexContent&gt;
     *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
     *       &lt;sequence&gt;
     *         &lt;element name="allowCreate" type="{http://www.w3.org/2001/XMLSchema}boolean"/&gt;
     *         &lt;element name="allowDelete" type="{http://www.w3.org/2001/XMLSchema}boolean"/&gt;
     *         &lt;element name="allowEdit" type="{http://www.w3.org/2001/XMLSchema}boolean"/&gt;
     *         &lt;element name="allowRead" type="{http://www.w3.org/2001/XMLSchema}boolean"/&gt;
     *         &lt;element name="modifyAllRecords" type="{http://www.w3.org/2001/XMLSchema}boolean"/&gt;
     *         &lt;element name="object" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
     *         &lt;element name="viewAllRecords" type="{http://www.w3.org/2001/XMLSchema}boolean"/&gt;
     *       &lt;/sequence&gt;
     *     &lt;/restriction&gt;
     *   &lt;/complexContent&gt;
     * &lt;/complexType&gt;
     * </pre>
     * 
     * 
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = {
        "allowCreate",
        "allowDelete",
        "allowEdit",
        "allowRead",
        "modifyAllRecords",
        "object",
        "viewAllRecords"
    })
    public static class ObjectPermissions {

        protected boolean allowCreate;
        protected boolean allowDelete;
        protected boolean allowEdit;
        protected boolean allowRead;
        protected boolean modifyAllRecords;
        @XmlElement(required = true)
        protected String object;
        protected boolean viewAllRecords;

        /**
         * Gets the value of the allowCreate property.
         * 
         */
        public boolean isAllowCreate() {
            return allowCreate;
        }

        /**
         * Sets the value of the allowCreate property.
         * 
         */
        public void setAllowCreate(boolean value) {
            this.allowCreate = value;
        }

        /**
         * Gets the value of the allowDelete property.
         * 
         */
        public boolean isAllowDelete() {
            return allowDelete;
        }

        /**
         * Sets the value of the allowDelete property.
         * 
         */
        public void setAllowDelete(boolean value) {
            this.allowDelete = value;
        }

        /**
         * Gets the value of the allowEdit property.
         * 
         */
        public boolean isAllowEdit() {
            return allowEdit;
        }

        /**
         * Sets the value of the allowEdit property.
         * 
         */
        public void setAllowEdit(boolean value) {
            this.allowEdit = value;
        }

        /**
         * Gets the value of the allowRead property.
         * 
         */
        public boolean isAllowRead() {
            return allowRead;
        }

        /**
         * Sets the value of the allowRead property.
         * 
         */
        public void setAllowRead(boolean value) {
            this.allowRead = value;
        }

        /**
         * Gets the value of the modifyAllRecords property.
         * 
         */
        public boolean isModifyAllRecords() {
            return modifyAllRecords;
        }

        /**
         * Sets the value of the modifyAllRecords property.
         * 
         */
        public void setModifyAllRecords(boolean value) {
            this.modifyAllRecords = value;
        }

        /**
         * Gets the value of the object property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getObject() {
            return object;
        }

        /**
         * Sets the value of the object property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setObject(String value) {
            this.object = value;
        }

        /**
         * Gets the value of the viewAllRecords property.
         * 
         */
        public boolean isViewAllRecords() {
            return viewAllRecords;
        }

        /**
         * Sets the value of the viewAllRecords property.
         * 
         */
        public void setViewAllRecords(boolean value) {
            this.viewAllRecords = value;
        }

    }


    /**
     * <p>Java class for anonymous complex type.
     * 
     * <p>The following schema fragment specifies the expected         content contained within this class.
     * 
     * <pre>
     * &lt;complexType&gt;
     *   &lt;complexContent&gt;
     *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
     *       &lt;sequence&gt;
     *         &lt;element name="apexPage" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
     *         &lt;element name="enabled" type="{http://www.w3.org/2001/XMLSchema}boolean"/&gt;
     *       &lt;/sequence&gt;
     *     &lt;/restriction&gt;
     *   &lt;/complexContent&gt;
     * &lt;/complexType&gt;
     * </pre>
     * 
     * 
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = {
        "apexPage",
        "enabled"
    })
    public static class PageAccesses {

        @XmlElement(required = true)
        protected String apexPage;
        protected boolean enabled;

        /**
         * Gets the value of the apexPage property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getApexPage() {
            return apexPage;
        }

        /**
         * Sets the value of the apexPage property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setApexPage(String value) {
            this.apexPage = value;
        }

        /**
         * Gets the value of the enabled property.
         * 
         */
        public boolean isEnabled() {
            return enabled;
        }

        /**
         * Sets the value of the enabled property.
         * 
         */
        public void setEnabled(boolean value) {
            this.enabled = value;
        }

    }


    /**
     * <p>Java class for anonymous complex type.
     * 
     * <p>The following schema fragment specifies the expected         content contained within this class.
     * 
     * <pre>
     * &lt;complexType&gt;
     *   &lt;complexContent&gt;
     *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
     *       &lt;sequence&gt;
     *         &lt;element name="default" type="{http://www.w3.org/2001/XMLSchema}boolean"/&gt;
     *         &lt;element name="personAccountDefault" type="{http://www.w3.org/2001/XMLSchema}boolean" minOccurs="0"/&gt;
     *         &lt;element name="recordType" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
     *         &lt;element name="visible" type="{http://www.w3.org/2001/XMLSchema}boolean"/&gt;
     *       &lt;/sequence&gt;
     *     &lt;/restriction&gt;
     *   &lt;/complexContent&gt;
     * &lt;/complexType&gt;
     * </pre>
     * 
     * 
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = {
        "_default",
        "personAccountDefault",
        "recordType",
        "visible"
    })
    public static class RecordTypeVisibilities {

        @XmlElement(name = "default")
        protected boolean _default;
        protected Boolean personAccountDefault;
        @XmlElement(required = true)
        protected String recordType;
        protected boolean visible;

        /**
         * Gets the value of the default property.
         * 
         */
        public boolean isDefault() {
            return _default;
        }

        /**
         * Sets the value of the default property.
         * 
         */
        public void setDefault(boolean value) {
            this._default = value;
        }

        /**
         * Gets the value of the personAccountDefault property.
         * 
         * @return
         *     possible object is
         *     {@link Boolean }
         *     
         */
        public Boolean isPersonAccountDefault() {
            return personAccountDefault;
        }

        /**
         * Sets the value of the personAccountDefault property.
         * 
         * @param value
         *     allowed object is
         *     {@link Boolean }
         *     
         */
        public void setPersonAccountDefault(Boolean value) {
            this.personAccountDefault = value;
        }

        /**
         * Gets the value of the recordType property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getRecordType() {
            return recordType;
        }

        /**
         * Sets the value of the recordType property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setRecordType(String value) {
            this.recordType = value;
        }

        /**
         * Gets the value of the visible property.
         * 
         */
        public boolean isVisible() {
            return visible;
        }

        /**
         * Sets the value of the visible property.
         * 
         */
        public void setVisible(boolean value) {
            this.visible = value;
        }

    }


    /**
     * <p>Java class for anonymous complex type.
     * 
     * <p>The following schema fragment specifies the expected         content contained within this class.
     * 
     * <pre>
     * &lt;complexType&gt;
     *   &lt;complexContent&gt;
     *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
     *       &lt;sequence&gt;
     *         &lt;element name="tab" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
     *         &lt;element name="visibility" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
     *       &lt;/sequence&gt;
     *     &lt;/restriction&gt;
     *   &lt;/complexContent&gt;
     * &lt;/complexType&gt;
     * </pre>
     * 
     * 
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = {
        "tab",
        "visibility"
    })
    public static class TabVisibilities {

        @XmlElement(required = true)
        protected String tab;
        @XmlElement(required = true)
        protected String visibility;

        /**
         * Gets the value of the tab property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getTab() {
            return tab;
        }

        /**
         * Sets the value of the tab property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setTab(String value) {
            this.tab = value;
        }

        /**
         * Gets the value of the visibility property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getVisibility() {
            return visibility;
        }

        /**
         * Sets the value of the visibility property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setVisibility(String value) {
            this.visibility = value;
        }

    }


    /**
     * <p>Java class for anonymous complex type.
     * 
     * <p>The following schema fragment specifies the expected         content contained within this class.
     * 
     * <pre>
     * &lt;complexType&gt;
     *   &lt;complexContent&gt;
     *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
     *       &lt;sequence&gt;
     *         &lt;element name="enabled" type="{http://www.w3.org/2001/XMLSchema}boolean"/&gt;
     *         &lt;element name="name" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
     *       &lt;/sequence&gt;
     *     &lt;/restriction&gt;
     *   &lt;/complexContent&gt;
     * &lt;/complexType&gt;
     * </pre>
     * 
     * 
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = {
        "enabled",
        "name"
    })
    public static class UserPermissions {

        protected boolean enabled;
        @XmlElement(required = true)
        protected String name;

        /**
         * Gets the value of the enabled property.
         * 
         */
        public boolean isEnabled() {
            return enabled;
        }

        /**
         * Sets the value of the enabled property.
         * 
         */
        public void setEnabled(boolean value) {
            this.enabled = value;
        }

        /**
         * Gets the value of the name property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getName() {
            return name;
        }

        /**
         * Sets the value of the name property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setName(String value) {
            this.name = value;
        }

    }

}
