name: build
on:
  push:
    branches:
      - master
  pull_request:

env:
  BUILD_VERSION: 1
  BUILD_NUM: ${BUILD_VERSION}.${GITHUB_RUN_ID}-RELEASE
  SERVICE_ACCOUNT_PAT_TOKEN: ${{ secrets.SERVICE_ACCOUNT_PAT_TOKEN }}
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-java@v1
        with:
          java-version: '11'
      - name: Build
        run: |
          mvn -B clean install -s settings-ci.xml
  deploy:
    name: Publish - GitHub Packages
    runs-on: ubuntu-latest
    needs: [build]
    if: github.ref == 'refs/heads/master'
    steps:
      - uses: actions/checkout@v1
      - name: Set up JDK
        uses: actions/setup-java@v1
        with:
          java-version: '11'
      - name: Publish artifact on GitHub Packages
        run: |
          mvn -B deploy -s settings-ci.xml
